function psp_compcoh1(f,cl,freq,max_cmp,label)
% psp_compcoh1(f,cl,freq,max_cmp,label)
% Function to plot results of difference of coherence test
%  in current figure/subplot window.
% Use to plot output of sp2_compcoh() function.
% This version based on hypothesis of equal coherence, i.e. difference of coherence = 0.
% 
% Copyright (C) 2008, David M. Halliday.
% This file is part of NeuroSpec.
%
%    NeuroSpec is free software; you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation; either version 2 of the License, or
%    (at your option) any later version.
%
%    NeuroSpec is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with NeuroSpec; if not, write to the Free Software
%    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%    NeuroSpec is available at:  http://www.neurospec.org/
%    Contact:  contact@neurospec.org
%
% f,cl     Output from difference of coherence routine, sp2_compcoh().
% freq     Frequency limit for plotting (Hz).
% max_cmp  Optional limits for y axis, should be +ve.
% label    Optional title instead of cl.what.
%
% psp_compcoh1(f,cl,freq,max_cmp,label)

if (nargin<3)
  error('Not enough input arguments')
end  

%freq_pts=round(freq/cl.df);
%Updated to support type 2 analysis
f_start=f(1,1,1);
freq_pts=round((freq-f_start)/cl.df)+1;

% Check this is output from sp2_compcoh.m
if (isfield(cl,'cmpcoh_c95')==0)
  error('Results not generated by sp2_compcoh.m');
end
%Check freq range
[x,y]=size(f);
if (freq_pts>x)
  error('Requested frequency range too large.');
end
if (freq_pts<1)
  error('Requested frequency range too narrow.');
end

f_max=freq_pts*cl.df;
uline=[f_start  cl.cmpcoh_c95; f_max  cl.cmpcoh_c95]; % Upper 95% confidence limit
lline=[f_start -cl.cmpcoh_c95; f_max -cl.cmpcoh_c95]; % Lower  95% confidence limit
zline=[f_start         0.0000; f_max         0.0000]; % Zero line, NULL value
plot(f(1:freq_pts,1),f(1:freq_pts,2),'k-',...
     uline(:,1),uline(:,2),'k-',...
     lline(:,1),lline(:,2),'k-',...
     zline(:,1),zline(:,2),'k--')
if nargin>3
  axis([0,freq,-max_cmp,+max_cmp]);
else  
  axis([0,freq,-Inf,Inf]);
end
xlabel('Frequency (Hz)')

if (nargin>4)
  title(label);
else
 title(['cmpcoh: ',cl.what]);
end  